version: '3.8'

services:
  pgdb:
    container_name: pgdb_prod
    image: postgres:15.4-alpine
    restart: always
    env_file:
      - ./producer/.env
    environment:
      - ./producer/.env
    volumes:
      - pgdb_pr:/var/lib/postgresql/data
    ports:
      - "5437:5432"
    networks:
      - kafka_network

  django:
    container_name: backend_producer
    build:
      dockerfile: Dockerfile
      context: .
    image: producer_backend:latest
    volumes:
      - static_volume:/var/www/producer/static
      - media_volume:/var/www/producer/media
    env_file:
      - ./producer/.env
    expose:
      - 8000
    depends_on:
      - pgdb
    networks:
      - kafka_network

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./docker/nginx/
    container_name: nginx_producer
    image: nginx-producer:latest
    volumes:
      - static_volume:/var/www/producer/static
      - media_volume:/var/www/producer/media
    ports:
      - "8000:80"
    depends_on:
      - django
    networks:
      - kafka_network

volumes:
  static_volume:
  media_volume:
  pgdb_pr:

networks:
  kafka_network:
    name: kafka_docker
    external: true
