# Generated by Django 5.0.4 on 2024-04-18 14:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=150, unique=True, verbose_name='transaction_id')),
                ('timestamp', models.DateTimeField(verbose_name='дата/время')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='сумма чека')),
                ('nds_amount', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='сумма НДС')),
                ('tips_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='сумма чаевых')),
                ('payment_method', models.CharField(max_length=20, verbose_name='метод оплаты')),
                ('place_id', models.CharField(max_length=150, verbose_name='Идентификатор места')),
                ('place_name', models.CharField(max_length=150, verbose_name='Название места покупки')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['id', 'transaction_id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=150, verbose_name='product_id')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='цена')),
                ('category', models.CharField(max_length=150, verbose_name='категория')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checks.transaction', to_field='transaction_id', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['id', 'product_id'],
            },
        ),
    ]
