version: '3.8'

services:
  pgdb:
    container_name: pgdb_cons
    image: postgres:15.4-alpine
    restart: always
    env_file:
      - ./consumer/.env
    environment:
      - ./consumer/.env
    volumes:
      - pgdb:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    networks:
      - default

  redis:
    image: redis
    container_name: redis
    networks:
      - default
    expose:
      - 6379
#    ports:
#      - "6379:6379"

  django:
    container_name: backend_consumer
    build:
      dockerfile: Dockerfile
      context: .
    image: consumer_backend:latest
    volumes:
      - .journal:/var/www/consumer/journal
      - static_volume:/var/www/consumer/static
      - media_volume:/var/www/consumer/media
    env_file:
      - ./consumer/.env
    expose:
      - 9000
    depends_on:
      - pgdb
    networks:
      - kafka_network
      - default

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./docker/nginx/
    container_name: nginx_consumer
    image: nginx-consumer:latest
    volumes:
      - static_volume:/var/www/consumer/static
      - media_volume:/var/www/consumer/media
    ports:
      - "9000:80"
    depends_on:
      - django
    networks:
      - kafka_network
      - default

volumes:
  static_volume:
  media_volume:
  pgdb:

networks:
  kafka_network:
    name: kafka_docker
    external: true
