# Generated by Django 5.0.4 on 2024-04-18 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150, verbose_name='категория')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id', 'location'],
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=150, verbose_name='Идентификатор места')),
                ('place_name', models.CharField(max_length=150, verbose_name='Название места покупки')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='сумма чека')),
                ('nds_amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='сумма НДС')),
                ('tips_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='сумма чаевых')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'ordering': ['id', 'place_id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=150, unique=True, verbose_name='Идентификатор места')),
                ('place_name', models.CharField(max_length=150, verbose_name='Название места покупки')),
                ('total_purchases', models.IntegerField(default=0, verbose_name='Кол-во покупок')),
                ('average_receipt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Средний чек')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
                'ordering': ['id', 'place_id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryAnalytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма за время')),
                ('average_receipt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Средний чек по категории')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_analytics', to='analytics.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Данные по категории',
                'verbose_name_plural': 'Данные по категориям',
                'ordering': ['id', 'cat'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='цена')),
                ('category', models.CharField(max_length=150, verbose_name='категория')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('to_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='analytics.check', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['id', 'category'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_analytics', to='analytics.purchaselocation', to_field='place_id', verbose_name='место покупки'),
        ),
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_nds', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма НДС за время')),
                ('total_tips', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма чаевых за время')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes_amount', to='analytics.purchaselocation', to_field='place_id', verbose_name='Налоги и чаевые')),
            ],
            options={
                'verbose_name': 'Налог',
                'verbose_name_plural': 'Налоги',
                'ordering': ['id', 'location'],
            },
        ),
    ]
