# Generated by Django 5.0.4 on 2024-04-18 11:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150, verbose_name='категория')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id', 'location'],
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=150, verbose_name='Идентификатор места')),
                ('place_name', models.CharField(max_length=150, verbose_name='Название места покупки')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='сумма чека')),
                ('nds_amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='сумма НДС')),
                ('tips_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='сумма чаевых')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'ordering': ['id', 'place_id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=150, unique=True, verbose_name='Идентификатор места')),
                ('place_name', models.CharField(max_length=150, verbose_name='Название места покупки')),
                ('total_purchases', models.IntegerField(default=0, verbose_name='Кол-во покупок')),
                ('average_receipt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Средний чек')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
                'ordering': ['id', 'place_id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('analytic', models.BooleanField(default=False, verbose_name='Аналитик')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CategoryAnalytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма за время')),
                ('average_receipt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Средний чек по категории')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_analytics', to='analytics.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Данные по категории',
                'verbose_name_plural': 'Данные по категориям',
                'ordering': ['id', 'cat'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='цена')),
                ('category', models.CharField(max_length=150, verbose_name='категория')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('to_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='analytics.check', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['id', 'category'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_analytics', to='analytics.purchaselocation', to_field='place_id', verbose_name='место покупки'),
        ),
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_nds', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма НДС за время')),
                ('total_tips', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма чаевых за время')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes_amount', to='analytics.purchaselocation', to_field='place_id', verbose_name='Налоги и чаевые')),
            ],
            options={
                'verbose_name': 'Налог',
                'verbose_name_plural': 'Налоги',
                'ordering': ['id', 'location'],
            },
        ),
    ]
