# Generated by Django 5.0.4 on 2024-04-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Общая стоимость'),
        ),
        migrations.AlterField(
            model_name='categoryanalytic',
            name='average_receipt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Средний чек по категории'),
        ),
        migrations.AlterField(
            model_name='categoryanalytic',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма за время'),
        ),
    ]
