# Generated by Django 5.0.4 on 2024-04-17 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_product_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_cost',
        ),
    ]
