# Generated by Django 5.0.4 on 2024-04-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_remove_product_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата записи'),
        ),
        migrations.AddField(
            model_name='categoryanalytic',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата записи'),
        ),
        migrations.AddField(
            model_name='purchaselocation',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата записи'),
        ),
        migrations.AddField(
            model_name='taxes',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата записи'),
        ),
    ]
