# Generated by Django 5.0.4 on 2024-04-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_category_date_create_categoryanalytic_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='categoryanalytic',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='purchaselocation',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата записи'),
        ),
    ]
